### ISSUE TITLE
[Question] Why Equatable?

### ISSUE THREAD

**Issue by wow-such-amazing** [mecid/swift-unidirectional-flow#12]
Hey @mecid! 

I've been having a look at your library and also at the TCA. And I've been wondering what's the idea behind making `State` and `Action` `Equatable`? 

One idea I have in mind is that such approach could help during testing to compare one state to another. But are there other benefit to making it `Equatable`?

I also can see that, even though actions and states are `Equatable` in the demo project, there are no requirements on the Architecture level for those types to be `Equatable`.

If you could share your thoughts on this that would be awesome 🙌 

Cheers!

**Comment by mecid** [comment]
@wow-such-amazing Hello,
There is no requirements on making state and actions equatable. But this improves testability and performance while SwiftUI checking states for the changes.
