### ISSUE TITLE
How do Middleware’s and Prism’s work?

### ISSUE THREAD

**Issue by toofunky** [mecid/swift-unidirectional-flow#13]
This is a fantastic framework. I’ve started using it in my project, and it works very well. This is not really an issue, but I’m wondering what an example Middleware would look like if it had more than one function? I’m new to Swift, and I’m not following why the example SearchMiddleware needs the additional complication of dependencies (I’m sure there’s a good reason). Is the idea that each Middleware does one thing? Also what is a Prism’s purpose?

**Comment by mecid** [comment]
Hello @toofunky, Middleware similar to Reducer can handle more than one action. For more information, check the tests folder for Store and Middleware.
