### ISSUE TITLE
Indirect actions in UDF

### ISSUE THREAD

**Issue by Woit** [mecid/swift-unidirectional-flow#15]
Hi! I have question about middlewares: one of middleware is a class, which is initialize a socket (let say after action ".startConnection(host: post:)" and then return action "done". 
The socket (which is hidden in middleware as "private var") receives some data from network and wants fire a new event. How it should be processed? For now im think that middleware should keep some reference to store's sendAction method. But it looks wrong.
So im trying to find a way to send action "indirectly". From the middleware's point of view it will looks like middleware returns action for some previous action, and then dispatched others actions if future. 
What did i miss?

**Comment by mecid** [comment]
Hi @Woit,
`Store` is not designed to handle long running tasks like socket connection. The way I would build this use-case is the handling web socket outside of the `Store` and feeding actions into to the `Store` as soon as event happens from socket handler.
