### ISSUE TITLE
How about bigger state?

### ISSUE THREAD

**Issue by adriantabirta** [mecid/swift-unidirectional-flow#2]
Nice example of UDF & swiftUI, but:

- is there any way / suggestions how to keep state in bigger apps? (I saw that state can derive from another but, I'm afraid of later mess) 
- what about navigation state (should it be part of main state) with newest swiftUI NavigationStack?
- for big lists with images & stuff how does it affects performance and memory footprint?
- did you have other examples of bigger apps, how did they avoid complex state? 

I`m just courios & afraid to take risks to implement smth new :)

**Comment by mecid** [comment]
@adriantabirta in my apps I use a store per feature approach which is super-efficient.
I don't usually keep navigation state or any other part of UI state(like selected item) in the store.
