### ISSUE TITLE
Possible infinite recursion in Store::send

### ISSUE THREAD

**Issue by aatriff** [mecid/swift-unidirectional-flow#4]
send function blocks caller until all middlewares returns their action, and untill all those action will be proceeded.

First problem (is it problem?) is that this behaviour violates FIFO order of messages sent to Store.

Second problem is possible infinite recursion, when middleware returns same action which starts it. Cos initial send will wait until all middlewares' result will be proceeded, same action will create recursion loop.
May be i do it wrong, but i can imagine situation, when i send .seacrQuery action at the app loding, and then send it again, after initial loading fails (no internet connection).

Are there any problems with such send fucntion?

```swift
public func send(_ action: Action) {
        state = reducer.reduce(state: state, withAction:action)

        for m in middlewares {
            Task.detached { [self] in
                guard let newAction = await m.process(action: action) else {
                    return
                }
                await send(newAction)
            }
        }
    }
```

**Comment by mecid** [comment]
@aatriff withTaskGroup doesn't inherit parent's actor. So main thread shouldn't be blocked.
