### ISSUE TITLE
Add connectors to the store

### ISSUE THREAD

**Issue by apfelnutzer** [mecid/swift-unidirectional-flow#5]
I'm using this package in combination with the connectors you suggest [here](http://swiftwithmajid.com/2021/02/03/redux-like-state-container-in-swiftui-part4/) and I suggest to add them as an extension to the package.  I've changed the type of the `deriveAction` parameter of the `derive` function to `connector.connect(action: ) as! (C.ViewAction) -> Action?` (optional return parameter) to enable for view models that just connect to the global state, but do not define any actions (yet).

What do you think?

**Comment by mecid** [comment]
You can have the connect function as part of the Store type extension. I'm not sure if I will add it as part of the package.

**Comment by apfelnutzer** [comment]
That's how I integrated the connect function so far, but to allow for "empty" actions I'd need to adjust the `derived` function of the `Store` as well which I cannot do with an extension. I'd need to fork this repository or find another solution - but I wanted to obtain your opinion first.

**Comment by mecid** [comment]
@apfelnutzer You can achieve empty actions derived store like this:

```swift
func never<Action>(_ action: Never) -> Action {}
        
let noActionStore: Store<State, Never> = store.derived(
    deriveState: { $0 },
    deriveAction: never
)
```
