### ISSUE TITLE
What about side effects

### ISSUE THREAD

**Issue by st-small** [mecid/swift-unidirectional-flow#9]
In big project there are many business logic to request, update, format etc. data that shouldn't be support using reducer. There are side effects and the whole system may observe actions to do them in future. For example, my system ask network connection to get some data, receive it, update in system and more more different logic.

@mecid Could you explain how to implement universal side effects service to support these actions? I have tried to use middlewares but they don't satisfy me, looks ugly and are unreadable.

**Comment by mecid** [comment]
1. I don't use Store for data formatting. It is the responsibility of formatter types. I wrote about them [here](https://swiftwithmajid.com/2023/07/04/mastering-swift-foundation-formatter-api-custom-format-styles/)
2. For side effects, I use middleware. It can intercept actions to do async work and return another action.

I don't think that Store should observe the network, etc. I also feed external events into the Store by using actions. For example, I run an observer of transaction updates for StoreKit outside of the Store. As soon as any new transaction appears, I send an action to the Store.

![external-events-store](https://swiftwithmajid.com/public/store.png)

**Comment by st-small** [comment]
Thank you for answer. I understood but want to explore this issue more detail. Will try to use your approach in my pet project. Tank you very much!

**Comment by mecid** [comment]
@st-small You're welcome. I use the way I've described it in 3 of my projects and it works pretty well.
